// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtWSg2v7p4dgwN72DoWe0QP1u_jTnh8Dw',
    appId: '1:607039782215:web:9cafbdbf45a5aec2ec6062',
    messagingSenderId: '607039782215',
    projectId: 'fir-uasc14190036',
    authDomain: 'fir-uasc14190036.firebaseapp.com',
    storageBucket: 'fir-uasc14190036.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPIHpIZtHq41S3y3q8ZS5Tondi-GxByc',
    appId: '1:607039782215:android:8219b107da4b6284ec6062',
    messagingSenderId: '607039782215',
    projectId: 'fir-uasc14190036',
    storageBucket: 'fir-uasc14190036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6eA7jBzwn0Lm4vJlA_BDOLFv1vLTnMY',
    appId: '1:607039782215:ios:62ce318b31c74e42ec6062',
    messagingSenderId: '607039782215',
    projectId: 'fir-uasc14190036',
    storageBucket: 'fir-uasc14190036.appspot.com',
    iosClientId: '607039782215-3ulmt79e488s2tqb121bt8e8arvktr8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasAmbwC14190036',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ6eA7jBzwn0Lm4vJlA_BDOLFv1vLTnMY',
    appId: '1:607039782215:ios:62ce318b31c74e42ec6062',
    messagingSenderId: '607039782215',
    projectId: 'fir-uasc14190036',
    storageBucket: 'fir-uasc14190036.appspot.com',
    iosClientId: '607039782215-3ulmt79e488s2tqb121bt8e8arvktr8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasAmbwC14190036',
  );
}
